# This is a basic workflow that is manually triggered

name: RestartBackend

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  startRemote:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Run SSH command for stopping old process
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ~/BrettSpiel_Backend/deployment/shutdownServer.sh
        host: tispyl.uber.space
        username: tispyl
        privateKey: ${{ secrets.PRIVATE_KEY_RSA}}

    - name: Run SSH command for starting production backend
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ~/BrettSpiel_Backend/deployment/startServer.sh
        host: tispyl.uber.space
        username: tispyl
        privateKey: ${{ secrets.PRIVATE_KEY_RSA}}
