# This is a basic workflow that is manually triggered

name: StartBackend

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  startRemote:
    runs-on: ubuntu-latest
    steps:
    - name: Run SSH command for stopping old process
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: kill $(netstat -atulpn | grep '41920.*LISTEN.*[0-9]*/node' | sed -rn 's/^.*\s([0-9]*)\/node.*$/\1/p')
        host: tispyl.uber.space
        username: tispyl
        privateKey: ${{ secrets.PRIVATE_KEY_RSA}}
    - name: Run SSH command for starting production backend
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: cd ~/BrettSpiel_Backend && nohup npm run runProd &
        host: tispyl.uber.space
        username: tispyl
        privateKey: ${{ secrets.PRIVATE_KEY_RSA}}
